### ISSUE TITLE
Initialize a form

### ISSUE THREAD

**Issue by hantsy** [hantsy/cargotracker-regapp#1]
I added a `@PostConstruct` to initialize data into a form, but I found it did not work as expected.

https://github.com/hantsy/cargotracker-regapp/blob/master/src/main/java/org/eclipse/cargotrakcer/regapp/ui/HandlingReportController.java#L60

It is very strange the init method is called when hitting the submit button. 

```bash
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.ComboBox.setItems(javafx.collections.ObservableList)" because "this.eventTypeField" is null
    at org.eclipse.cargotrakcer.regapp.ui.HandlingReportController.init (HandlingReportController.java:61)
```

In the back of CDI and Java FX integration, I  used [javafx-weaver](https://github.com/rgielen/javafx-weaver) to load the controller class and FXML files.

https://github.com/hantsy/cargotracker-regapp/blob/master/src/main/java/org/eclipse/cargotrakcer/regapp/ui/PrimaryStageInitializer.java#L25

**Comment by rgielen** [comment]
`@PostConstruct` is most likely not the right solution here. It does not adhere to the JavaFX lifecycle and runs most probably on the wrong thread.

You should go for an JavaFX initialize() method, either by annotating it with `@FXML` or implementing `javafx.fxml.Initializable`

See https://stackoverflow.com/questions/34785417/javafx-fxml-controller-constructor-vs-initialize-method for details.

**Comment by hantsy** [comment]
@rgielen Thanks. Add a `@FXML private void initialize()` to resolve this issue.

I have tried to add initialize method before, but using the **public** modifier will cause Weld to create a proxy which will cause anther exception.
